#!/system/bin/sh

if [ "$1" == "" ] || [ "$1" == "rw" ]; then
  echo "Enabling read/write access to /system"
  mount -o remount,rw /system /system
fi
if [ "$1" == "ro" ]; then
  echo "Enabling read-only access to /system"
  mount -o remount,ro /system /system
fi